# Generated by Django 4.2 on 2025-02-20 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time_spent',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), help_text='HH:MM:SS', null=True),
        ),
    ]
