# Generated by Django 4.2 on 2025-01-27 00:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('bucket_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='image/webp', max_length=50)),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='attractions.attraction')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='threads.comment')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='threads.review')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'db_table': 'media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['file_url'], name='media_file_ur_0ba5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['bucket_name'], name='media_bucket__dbb840_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['file_type'], name='media_file_ty_da91ba_idx'),
        ),
    ]
