name: Backend app quality

on:
    pull_request:
      branches:
        - dev
        - main
        - master
    push:
        paths:
          - 'backend/**'
        ignore:
          - ".idea"
          - ".vscode"
          - ".qodo"
          - "mobile_expo/planer_app/**"

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11.7"
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Ser up Python
        uses: actions/setup-python@v5

  uv:
    runs-on: ubuntu-latest
    needs: python
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

  django:
    runs-on: ubuntu-latest
    needs: uv
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - dotenv/source:
          path: .env.development.local
      - name: Install dev dependencies
        run: |
          uv sync --frozen --no-install-project --group dev
      - name: Run django project
        run: |
          uv run python manage.py runserver 0.0.0.0:8000