name: Backend app quality

env:
    DOCKER_BUILDKIT: 1
    COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches:
      - dev
      - main
      - master
  push:
    paths:
      - '.github/**'
      - 'backend/**'

jobs:
  django:
    runs-on: ubuntu-latest
    env:
      CPLUS_INCLUDE_PATH: /usr/include/gdal
      C_INCLUDE_PATH: /usr/include/gdal
      DJANGO_SETTINGS_MODULE: core.settings.development
      ENVIRONMENT: development
      SECRET_KEY: app_secret_key
      DEBUG: 1
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: triplane
      POSTGRES_DB: postgres-triplane
      POSTGRES_PORT: 5432
      STORAGE_ENDPOINT_URL: http://localhost:9000
      STORAGE_ACCESS_KEY: superuser
      STORAGE_SECRET_KEY: superuser
      STORAGE_SECURE: "False"
      STORAGE_BUCKET_NAME: files
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Django
        run: docker compose --profile dev build
      - name: Stop Docker containers
        run: docker compose down